1. What is a Python library? Why do we use Python libraries?

In [ ]:
'''
A Python library is a collection of pre-written code that provides specific functionality, such as performing mathematical operations, interacting with databases, or creating web applications.
Libraries are organized in modules, which can be imported into a Python program to reuse code without needing to write it from scratch.

Python libraries are used for the following reasons:
* Efficiency: They save time by providing pre-built functions.
* Code Reusability: They reduce the need to write repetitive code.
* Functionality: They extend Python's capabilities by offering specialized tools.
* Community Support: Popular libraries often have strong community support, offering updates and improvements.
'''
pass


2. What is the difference between Numpy array and List?

The key differences between a NumPy array and a Python list are:

1. **Data Type**:  
   - **NumPy Array**: Requires all elements to be of the same data type (e.g., all integers or all floats).
   - **List**: Can contain elements of different data types (e.g., integers, floats, strings).

2. **Performance**:  
   - **NumPy Array**: Provides faster performance, especially for large datasets, because it is optimized for numerical operations.
   - **List**: Slower for numerical operations since it lacks optimization and performs element-wise operations.

3. **Functionality**:  
   - **NumPy Array**: Supports advanced mathematical operations (e.g., matrix operations, broadcasting).
   - **List**: Limited in built-in functionality for mathematical computations.

4. **Memory Usage**:  
   - **NumPy Array**: Consumes less memory because it is more efficient in storing data.
   - **List**: Consumes more memory due to its flexible data storage format.

5. **Dimensionality**:  
   - **NumPy Array**: Can handle multi-dimensional data (e.g., 2D arrays, 3D arrays).
   - **List**: Typically handles one-dimensional data; multi-dimensional lists are possible but less efficient.



3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [2]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Get the shape, size, and dimension
shape = arr.shape        # Shape of the array
size = arr.size          # Total number of elements
dimension = arr.ndim     # Dimension of the array

print("Shape:", shape)
print("Size:", size)
print("Dimension:", dimension)

Shape: (3, 4)
Size: 12
Dimension: 2


4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [3]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Access the first row
first_row = arr[0]

print("First Row:", first_row)

First Row: [1 2 3 4]


5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [4]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Access the element at the third row and fourth column
element = arr[2, 3]

print("Element at third row and fourth column:", element)

Element at third row and fourth column: 12


6. Write code to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [5]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Flatten the array and extract elements at odd indices
odd_indexed_elements = arr.flatten()[1::2]

print("Odd-indexed elements:", odd_indexed_elements)

Odd-indexed elements: [ 2  4  6  8 10 12]


7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [6]:
import numpy as np

# Generate a 3x3 matrix with random values between 0 and 1
random_matrix = np.random.rand(3, 3)

print("Random 3x3 Matrix:\n", random_matrix)

Random 3x3 Matrix:
 [[0.62126576 0.67439051 0.66329136]
 [0.32887315 0.00305938 0.88877627]
 [0.77565765 0.40731919 0.14952459]]


8. Describe the difference between np.random.rand and np.random.randn?

The difference between **np.random.rand** and **np.random.randn** in NumPy is:

- **np.random.rand()**

 - ***Distribution***: Generates random numbers from a uniform distribution between 0 and 1. This means each value has an equal probability of being selected from the interval [0, 1).
  - ***Range***: The values lie between 0 (inclusive) and 1 (exclusive).
  - ***Usage***: **np.random.rand(shape)** where **shape** defines the dimensions of the output array.


- **np.random.randn()**
 - ***Distribution***: Generates random numbers from a standard normal distribution (Gaussian distribution) with a mean of 0 and a standard deviation of 1.
 - ***Range***: The values can be both positive and negative, typically falling between -3 and 3, but theoretically extending to infinity in both directions.
 - ***Usage***: **np.random.randn(shape)** where **shape** defines the dimensions of the output array.

9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [7]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Increase the dimension (e.g., from 2D to 3D)
arr_expanded = np.expand_dims(arr, axis=0)  # Adds a new dimension at the beginning

print("Expanded Array:\n", arr_expanded)
print("New Shape:", arr_expanded.shape)

Expanded Array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
New Shape: (1, 3, 4)


10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [8]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Transpose the array
arr_transposed = np.transpose(arr)

print("Transposed Array:\n", arr_transposed)

Transposed Array:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


**11. Consider the following matrix:**

**Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]**

**Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]**

**Perform the following operation using Python:**

1. Index wise multiplication
2. Matrix multiplication
3. Add both the matrics
4. Subtract matrix B from A
5. Divide Matrix B by A

In [10]:
import numpy as np

# Define matrices A and B
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Index-wise (element-wise) multiplication
index_wise_multiplication = A * B

# Matrix multiplication
matrix_multiplication = np.dot(A, B.T)  # Transpose B for correct matrix multiplication

# Addition of matrices
matrix_addition = A + B

# Subtraction of matrix B from A
matrix_subtraction = A - B

# Element-wise division of B by A
element_wise_division = B / A

print("Index-wise Multiplication:\n", index_wise_multiplication)
print("Matrix Multiplication (Dot Product):\n", matrix_multiplication)
print("Matrix Addition:\n", matrix_addition)
print("Matrix Subtraction:\n", matrix_subtraction)
print("Element-wise Division (B / A):\n", element_wise_division)

Index-wise Multiplication:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
Matrix Multiplication (Dot Product):
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
Matrix Addition:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Matrix Subtraction:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Element-wise Division (B / A):
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


12. Which function in Numpy can be used to swap the byte order of an array?

In [11]:
import numpy as np

# Define an array with a specific byte order
arr = np.array([1, 2, 3, 4], dtype='>i4')  # Big-endian integer array

# Swap the byte order
arr_swapped = arr.byteswap()

print("Original Array:", arr)
print("Swapped Array:", arr_swapped)

Original Array: [1 2 3 4]
Swapped Array: [16777216 33554432 50331648 67108864]


13. What is the significance of the np.linalg.inv function?

The **np.linalg.inv** function in NumPy is used to compute the inverse of a square matrix. The inverse of a matrix **A** is another matrix A^-1 such that when multiplied together, they yield the identity matrix **I**, i.e., **A x A^-1 = I**

- Significance:
  - ***Solving Linear Systems***: The matrix inverse is used to solve systems of linear equations of the form Ax = b. If A is invertible, the solution can be found as x = A^(-1)b.
  - ***Matrix Operations***: Inverse matrices are important in various matrix operations and transformations, such as inverting transformations in graphics and physics simulations.
  - ***Stability and Conditioning***: The inverse of a matrix is crucial for understanding the stability and conditioning of a system. For example, in numerical analysis, the condition number of a matrix, which involves the inverse, provides insight into the sensitivity of the solution to changes in the input.


In [12]:
##Usage

import numpy as np

# Define a square matrix
A = np.array([[1, 2],
              [3, 4]])

# Compute the inverse
A_inv = np.linalg.inv(A)

print("Matrix A:\n", A)
print("Inverse of Matrix A:\n", A_inv)

Matrix A:
 [[1 2]
 [3 4]]
Inverse of Matrix A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


14. What does the np.reshape function do, and how is it used?

The **np.reshape** function in NumPy is used to change the shape of an existing array without modifying its data. It allows you to rearrange the elements of the array into a new shape, as long as the total number of elements remains the same.

- **Functionality:**
  - ***Change Dimensions***: Convert an array into a different number of dimensions or a different shape.
  - ***Flatten or Expand***: You can use it to flatten a multidimensional array into a 1D array or expand a 1D array into a multidimensional array.

In [14]:
##Example usage
import numpy as np

# Define a 1D array
arr = np.arange(12)  # Array with 12 elements: [0, 1, 2, ..., 11]

# Reshape the array into a 3x4 matrix
reshaped_arr = np.reshape(arr, (3, 4))

print("Original Array:\n", arr)
print("Reshaped Array:\n", reshaped_arr)

Original Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


15. What is broadcasting in Numpy?

Broadcasting in NumPy is a set of rules and techniques that allow NumPy to perform operations on arrays of different shapes in a way that is both efficient and intuitive. Broadcasting enables element-wise operations on arrays with different shapes by automatically expanding the smaller array to match the shape of the larger array.

**Key Concepts:**

- **Broadcasting Rules:**
  - ***Rule 1***: If the arrays have a different number of dimensions, the shape of the smaller-dimensional array is padded with ones on the left side until both shapes have the same length.
  - ***Rule 2***: If the shape of the arrays does not match, the dimensions of the arrays are compared element-wise. Two dimensions are compatible when: They are equal, or One of them is 1.
  - ***Rule 3***: If the dimensions are compatible, the smaller array is "broadcast" across the larger array so that they have the same shape.
- **Example of Broadcasting**: Suppose you have a 2D array and a 1D array, and you want to add them together. Broadcasting allows NumPy to automatically handle the shape mismatch.

In [15]:
##Example usage
import numpy as np

# Define a 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6]])

# Define a 1D array
array_1d = np.array([10, 20, 30])

# Perform addition using broadcasting
result = array_2d + array_1d

print("2D Array:\n", array_2d)
print("1D Array:\n", array_1d)
print("Result of Broadcasting:\n", result)

2D Array:
 [[1 2 3]
 [4 5 6]]
1D Array:
 [10 20 30]
Result of Broadcasting:
 [[11 22 33]
 [14 25 36]]
